### ISSUE TITLE
How Do I Access User/Specific Networks

### ISSUE THREAD

**Issue by tayb18** [tayb18/teachtogether#2]
Hi @annarankin ,

Remember when we were doing the index page for a users unit plans? We did something like this to tell the controller that we only want to see unit plans where user id = session id:

def index
    @unitplans = UnitPlan.where user_id: session[:user_id]
  end

Well I'm trying to do something similary with Networks. I want all the networks for that specific use. But the above example doesn't work because the network doesn't have a user id. I know,because I tried and failed and was like, oh yeah obviously that wouldn't work. Like so...

def index
    @networks = Networks.where user_id: session[:user_id]
  end

 Networks and users share a join table with network_id and user_id. 
 Anywho, if you have any insight, that would be great!

**Comment by tayb18** [comment]
Here's my beautiful error

![screen shot 2016-01-22 at 12 46 52 pm](https://cloud.githubusercontent.com/assets/15020181/12518383/440475b6-c106-11e5-8e6b-5c1fc701f11f.png)

**Comment by annarankin** [comment]
Hey Taylor, were you able to solve your error?
