### ISSUE TITLE
Hii Struggling to access user-specific networks

### ISSUE THREAD

**Issue by tayb18** [tayb18/teachtogether#3]
Hi @annarankin ,

Remember when we were doing the index page for a users unit plans? We did something like this to tell the controller that we only want to see unit plans where user id = session id:

def index
@unitplans = UnitPlan.where user_id: session[:user_id]
end

Well I'm trying to do something similary with Networks. I want all the networks for that specific use. But the above example doesn't work because the network doesn't have a user id. I know,because I tried and failed and was like, oh yeah obviously that wouldn't work. Like so...

def index
@networks = Networks.where user_id: session[:user_id]
end

Networks and users share a join table with network_id and user_id. 
Anywho, if you have any insight, that would be great!

Here's my lovely error 
![screen shot 2016-01-22 at 12 46 52 pm](https://cloud.githubusercontent.com/assets/15020181/12518860/22bc2662-c109-11e5-865f-fd2a4a62e5d5.png)

**Comment by annarankin** [comment]
Hey Taylor! Can you push up your recent code so I can take a look at it?

**Comment by tayb18** [comment]
Great idea, it's been pushed!

**Comment by annarankin** [comment]
Hey Taylor, a few notes as I look over your application -

Lines 70-72 in application.html.erb:

``` html
 <li>
    <!-- Watch that you're not using the :id syntax here - it's ERB, so you'll need squids -->
    <a href="/users/:id/networks">Networks</a>
</li>
```

To find all of the networks that belong to a user, try first finding the user and then calling `.networks` on the ActiveRecord object.
